# Pull base image.
FROM sherylynn/nodejs
MAINTAINER Sherylynn <352281674@qq.com>

# openjdk-8
RUN apk --update add --no-cache openjdk8
ENV JAVA8_HOME /usr/lib/jvm/default-jvm
ENV JAVA_HOME $JAVA8_HOME
