# Pull base image.
FROM sherylynn/wget
MAINTAINER Sherylynn <352281674@qq.com>

# 输入下载地址
RUN apk --update add --no-cache py-pip
RUN pip install shadowsocks
# 还不清楚怎么运行好
ADD supervisord.conf /etc/supervisord.conf